NO_DATA = "No data found"
QUESTION_ADDED = "Question added successfully"
QUESTION_UPDATE = "Question updated"
PARSLEY_REQUIRED = 'This field is required'
PARSLEY_MAXLENGTH = 'This field can have 500 characters maximum'
QUESTION_DELETED = 'Question deleted successfully'
QUESTION_UNIQUE = 'Question should be unique'
EXCEL_VALIDATION = 'This question can not link with Excel'
TYPING_VALIDATION = 'This question can not link with Typing Test'
