from selenium.webdriver.common.by import By


class Locators:
    ADD_NEW_QUESTION_BUTTON = (By.CSS_SELECTOR, 'button.AddRecordBtn')
    INPUT_SUBJECT = (By.ID, 'IBSQ_subject')
    INPUT_QUESTION_TITLE = (By.ID, 'IBSQ_question')
    INPUT_ANSWER_KEYS = (By.ID, 'IBSQ_answer_key')
    INPUT_IMAGE = (By.XPATH, '//input[@type="file"]')
    SAVE_BUTTON = (By.ID, 'save-button')
    CLOSE_BUTTON = (By.ID, 'close-button')
    DISPLAY_MESSAGE = (By.ID, 'notice')
    PARSLEY_REQUIRED = (By.CLASS_NAME, 'parsley-required')
    PARSLEY_MAXFILESIZE = (By.CLASS_NAME, 'parsley-maxFileSize')
    PARSLEY_FILEEXTENSION = (By.CLASS_NAME, 'parsley-fileextension')
    GET_QUESTION_TEXT = (By.CSS_SELECTOR, 'td.EditData')
    PARSLEY_PATTERN = (By.CLASS_NAME, 'parsley-pattern')
    TABLE_ROW_COUNT = (By.CSS_SELECTOR, 'tbody#demo tr')
    DELETE_BUTTON = (By.ID, 'Delete')
    PARSLEY_MAXLENGTH = (By.CLASS_NAME, 'parsley-maxlength')
    EDIT_BUTTON = (By.CSS_SELECTOR, 'a.Edit')
    
class SubjectPageLocators:
    INPUT_SUBJECT = (By.NAME, 'subject')
    EDIT_BUTTON = (By.CSS_SELECTOR, 'span.editButton')
    GET_TEXT_SUBJECT = (By.XPATH, '//*[@id="demo"]/tr[1]/td[1]')
    
class LoginPageLocators:
    INPUT_USERNAME = (By.NAME, 'username')
    INPUT_PASSWORD = (By.NAME, 'password')
    LOGIN_BUTTON = (By.ID, 'login_button')
    CLICK_TEXT_ALLOW_AUTHENTICATED_USER_XPATH = (By.LINK_TEXT, 'Allow Authenticated User')
    CLICK_TEXT_ADD_SUBJECT_XPATH = (By.LINK_TEXT, 'Add Subject')
    CLICK_TEXT_MULTIPLE_IMAGE_CHOICE_QUESTION_XPATH = (By.LINK_TEXT, 'Multiple Image Choice Question')
    CLICK_TEXT_MULTIPLE_CHOICE_QUESTION_XPATH = (By.LINK_TEXT, 'Multiple Choice Question')
    CLICK_TEXT_IMAGE_BASED_MULTIPLE_CHOICE_QUESTION_XPATH = (By.LINK_TEXT, 'Image Based Multiple Choice Questions')
    CLICK_TEXT_SUBJECTIVE_QUESTION_XPATH = (By.LINK_TEXT, 'Subjective Questions')
    CLICK_TEXT_IMAGE_BASED_SUBJECTIVE_QUESTION_XPATH = (By.LINK_TEXT, 'Image Based Subjective Questions')
        
class SubjectiveQuestionPageLocators:
    INPUT_SUBJECT = (By.ID, 'id_subjects')
    INPUT_PASSAGE = (By.ID, 'id_passage')
    INPUT_QUESTION_TITLE = (By.ID, 'id_question_title')
    INPUT_ANSWER_KEY = (By.ID, 'id_answer_key')
    INPUT_INSTRUCTION =(By.ID, 'id_instructions')
    SAVE_BUTTON = (By.ID, 'add_question_btn')
    CLOSE_BUTTON = (By.ID, 'close-dialoge')
    SEARCH_BY_QUESTION = (By.ID, 'searchquestion')
    SEARCH_BY_SUBJECT = (By.ID, 'id_question_id')
    SEARCH_BUTTON = (By.XPATH, '//button[@value="Search"]')
    EDIT_BUTTON = (By.CSS_SELECTOR, 'span.editButton')
    
class ImageBasedMultipleChoiceQuestionPageLocators:
    INPUT_SUBJECT = (By.ID,'image_MCQ_subject')
    INPUT_QUESTION_TITLE = (By.ID,'image_MCQ_title')
    OPTIONA = (By.ID,'image_MCQ_optionA')
    OPTIONB = (By.ID,'image_MCQ_optionB')
    OPTIONC = (By.ID,'image_MCQ_optionC')
    OPTIOND = (By.ID,'image_MCQ_optionD')
    CHECKED_ON_CORRECT_OPTION = (By.ID, 'chkboxOption2')
    IMAGE_UPLOAD = (By.ID, 'MCQ_image_upload')
    GET_QUESTION_TEXT = (By.CSS_SELECTOR, 'td h5')
    SEARCH_BY_QUESTION_TITLE = (By.ID, 'id_question_title')
    SEARCH_BY_SUBJECT = (By.ID, 'id_subject')
    SEARCH_BUTTON = (By.CSS_SELECTOR, 'input.btn-primary')
    
class AllowAuthenticatedUserPageLocators:
    ADD_USER_BUTTON = (By.ID, 'addButton')
    INPUT_USERNAME = (By.ID, 'userSettingUsername')
    INPUT_EMAIL = (By.ID, 'userSettingEmail')
    INPUT_ROLE = (By.ID, 'userSettingRole')
    INPUT_STATUS = (By.ID, 'userSettingStatus')
    SEARCH_USERNAME = (By.ID, 'id_username')
    SEARCH_EMAIL = (By.ID, 'id_email')
    SEARCH_ROLE = (By.ID, 'id_role')
    SEARCH_BUTTON = (By.XPATH, '//input[@value="Search"]')
    DISPLAY_USERNAME_TABLE = (By.TAG_NAME, 'td')
    DISPLAY_EMAIL_TABLE = (By.ID, 'email_column')
    DISPLAY_ROLE_TABLE = (By.ID, 'role_column')
    CLICK_EDIT_BUTTON_SELECT_ROLE_DROPDOWN = (By.XPATH, '//select[@id="userSettingRole"]/option[1]')
    CLICK_EDIT_BUTTON_SELECT_STATUS_DROPDOWN = (By.XPATH, '//select[@id="userSettingStatus"]/option[1]')

class MultipleChoiceQuestionPageLocators:
    INPUT_SUBJECT = (By.ID, 'MCQ_subject')
    INPUT_PASSAGE = (By.ID, 'MCQ_passage')
    INPUT_QUESTION_TITLE = (By.ID, 'MCQ_title')
    INPUT_OPTION_A = (By.ID, 'MCQ_optionA')
    INPUT_OPTION_B = (By.ID, 'MCQ_optionB')
    INPUT_OPTION_C = (By.ID, 'MCQ_optionC')
    INPUT_OPTION_D = (By.ID, 'MCQ_optionD')
    DELETE_BUTTON = (By.CLASS_NAME, 'btn-danger')
    SEARCH_BY_QUESTION_TITLE = (By.ID, 'MCQ_title_search')
    SEARCH_BY_SUBJECT = (By.ID, 'MCQ_subject_search')
    EDIT_BUTTON = (By.CSS_SELECTOR, 'a.edit_mcq')
    
class MultipleImageChoiceQuestionPageLocators:
    INPUT_QUESTION_TITLE = (By.ID, 'MICQ_title')
    INPUT_SUBJECT = (By.XPATH, '//select[@id="MICQ_subject"]/option[5]')
    INPUT_OPTION_A = (By.ID, 'MICQ_optionA')
    INPUT_OPTION_B = (By.ID, 'MICQ_optionB')
    INPUT_OPTION_C = (By.ID, 'MICQ_optionC')
    INPUT_OPTION_D = (By.ID, 'MICQ_optionD')
    CHECKED_ON_CORRECT_OPTION = (By.ID, 'chkboxOption1')
    GET_QUESTION_TEXT = (By.XPATH, '//*[@id="demo"]/tr[1]/td[1]')
    CLICK_EDIT_BUTTON_SELECT_SUBJECT_DROPDOWN = (By.XPATH, '//select[@id="MICQ_subject"]/option[1]')
    UPDATE_INPUT_SUBJECT = (By.XPATH, '//select[@id="MICQ_subject"]/option[6]')
